### ISSUE TITLE
lwwdg_process should use LWWDG_GET_TIME in critical section

### ISSUE THREAD

**Issue by radonyl** [MaJerle/lwwdg#1]
## description

- `lwwdg_process` got a `time_curr` < `last_reload_time`, `WDG_IS_EXPIRED` got a huge negative overflow value and return true, causing unexpected system reset
<img width="1238" alt="image" src="https://github.com/MaJerle/lwwdg/assets/19205327/43a3f330-2d0a-4ef6-80c8-56b93cd45cd9">

## platform information 

- lwwdg version: 1.1.1
- FreeRTOS version V10.3.1, **tickless idle** enabled, handled by [LPTIM-Tick](https://github.com/jefftenney/LPTIM-Tick)
- MCU: STM32G071

## steps to reproduce:

1. setup some tasks, and run `lwwdg_process` in `wdg_task` which has a priority equal to idle task
2. set a breakpoint when `lwwdg_process` set `failed = 1`
3. run until the breakpoint is triggered

## possible cause

- after `time_curr = LWWDG_GET_TIME();`,  scheduler interrupt `wdg_task` and run other tasks with higher priority, then `wdg_reload` was called in these tasks. This could will lead to `time_curr` slightly behind `last_reload_time`.

## possible fix

- in `lwwdg_process`, move `LWWDG_GET_TIME` into critical section

**Comment by MaJerle** [comment]
Agree. Fixed https://github.com/MaJerle/lwwdg/commit/0e2a0e3d779d66d2ad45fa3b4622b1c285ae2c2c
